Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  IgnoredPatterns:
    - 'http(?:s)?://'

Style/AsciiComments:
  Enabled: false

Style/AutoResourceCleanup:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
