AllCops:
  TargetRubyVersion: 2.3.7

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  IgnoredPatterns:
    - 'http(?:s)?://'

Metrics/ModuleLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2

Style/AndOr:
  EnforcedStyle: conditionals

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/LambdaCall:
  EnforcedStyle: braces

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
